### ISSUE TITLE
Use the server name instead of "Connected" as indicator status text

### ISSUE THREAD

**Issue by semente** [Pobega/gnome-shell-extension-mullvad-indicator#21]
Following the example of the other indicators in this menu (e.g. WiFi and bluetooth indicators which displays the device name), I would like to see the name of the server I'm connected to instead of "Connected".

What do you think? Thanks

![example](https://user-images.githubusercontent.com/29862/172884030-0dbf6ea5-3d23-403a-a56e-2c0f060aed86.png)

**Comment by Pobega** [comment]
![image](https://user-images.githubusercontent.com/474525/221600955-f69e1d67-26f2-42de-b6f4-b99181213fb1.png)

Sure, I went ahead and did it. The issue is that longer server names look pretty bad and you can't really add the state/country without it going far beyond the allowed text.

![image](https://user-images.githubusercontent.com/474525/221606128-7ddba032-eeea-4e2b-b72f-5644f000bace.png)

I've added it as an option in the settings.

https://github.com/Pobega/gnome-shell-extension-mullvad-indicator/commit/d09d6d7392c7f596f875e2f2b7c62f54b5f8827a
